# Generated by Django 3.2.6 on 2021-08-27 15:46

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/')),
                ('text', ckeditor.fields.RichTextField()),
                ('text_ru', ckeditor.fields.RichTextField(null=True)),
                ('text_az', ckeditor.fields.RichTextField(null=True)),
                ('text_en', ckeditor.fields.RichTextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_code', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('question_ru', models.CharField(max_length=255, null=True)),
                ('question_az', models.CharField(max_length=255, null=True)),
                ('question_en', models.CharField(max_length=255, null=True)),
                ('answer', models.TextField()),
                ('answer_ru', models.TextField(null=True)),
                ('answer_az', models.TextField(null=True)),
                ('answer_en', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaqImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='faq_image/')),
            ],
            options={
                'verbose_name_plural': 'Faq Image',
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_az', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(max_length=127)),
                ('description_ru', models.TextField(max_length=127, null=True)),
                ('description_az', models.TextField(max_length=127, null=True)),
                ('description_en', models.TextField(max_length=127, null=True)),
            ],
            options={
                'verbose_name_plural': 'Index',
            },
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('title_ru', models.CharField(max_length=127, null=True)),
                ('title_az', models.CharField(max_length=127, null=True)),
                ('title_en', models.CharField(max_length=127, null=True)),
                ('short_description', models.TextField(max_length=127)),
                ('short_description_ru', models.TextField(max_length=127, null=True)),
                ('short_description_az', models.TextField(max_length=127, null=True)),
                ('short_description_en', models.TextField(max_length=127, null=True)),
                ('number', models.IntegerField()),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='JoinTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('title_ru', models.CharField(max_length=127, null=True)),
                ('title_az', models.CharField(max_length=127, null=True)),
                ('title_en', models.CharField(max_length=127, null=True)),
                ('description', models.TextField(max_length=127)),
                ('description_ru', models.TextField(max_length=127, null=True)),
                ('description_az', models.TextField(max_length=127, null=True)),
                ('description_en', models.TextField(max_length=127, null=True)),
            ],
            options={
                'verbose_name_plural': 'Join Title',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_az', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('text', models.TextField()),
                ('text_ru', models.TextField(null=True)),
                ('text_az', models.TextField(null=True)),
                ('text_en', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WinnerCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RecentWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='user/')),
                ('time', models.DateTimeField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
