# Generated by Django 3.2.6 on 2021-08-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_az', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('information', models.CharField(max_length=255)),
                ('information_ru', models.CharField(max_length=255, null=True)),
                ('information_az', models.CharField(max_length=255, null=True)),
                ('information_en', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
