# Generated by Django 3.2.6 on 2021-08-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20210824_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_az', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('desc', models.TextField()),
                ('desc_ru', models.TextField(null=True)),
                ('desc_az', models.TextField(null=True)),
                ('desc_en', models.TextField(null=True)),
            ],
        ),
    ]
