# Generated by Django 3.2.6 on 2021-08-24 11:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('term_and_condination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicy',
            name='text_az',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='text_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='termandcondition',
            name='text_az',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='termandcondition',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='termandcondition',
            name='text_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
