# Generated by Django 3.2.6 on 2021-08-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField(blank=True, max_length=127, null=True)),
                ('image', models.ImageField(upload_to='blog_image', verbose_name='Image')),
                ('blog_card_title', models.CharField(blank=True, max_length=127, null=True)),
                ('description', models.TextField(blank=True, max_length=127, null=True)),
                ('slug', models.SlugField(max_length=150, verbose_name='Slug')),
                ('time', models.DateField(auto_now=True, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
