# Generated by Django 3.2.6 on 2021-08-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210818_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default=1, max_length=127),
            preserve_default=False,
        ),
    ]
