# Generated by Django 3.2.6 on 2021-08-20 08:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='short_description_az',
            field=models.TextField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='short_description_en',
            field=models.TextField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='short_description_ru',
            field=models.TextField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_az',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_az',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ru',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
