# Generated by Django 3.2.6 on 2021-08-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtitle',
            name='desc_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogtitle',
            name='desc_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogtitle',
            name='desc_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogtitle',
            name='title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogtitle',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogtitle',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
