# Generated by Django 3.2.6 on 2021-08-25 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_alter_ticket_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Number',
        ),
    ]
