# Generated by Django 3.2.6 on 2021-09-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0004_auto_20210826_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lottery',
            name='status',
        ),
    ]
